In [2]:
import pandas as pd

In [2]:
df = pd.read_csv("filtered_CNV.txt", sep="\t", header = 0)

In [3]:
print(len(df))
df.head()

6787

,#Uploaded_variation,Location,Allele,Consequence,IMPACT,SYMBOL,Gene,Feature_type,Feature,BIOTYPE,...,PUBMED,VAR_SYNONYMS,MOTIF_NAME,MOTIF_POS,HIGH_INF_POS,MOTIF_SCORE_CHANGE,TRANSCRIPTION_FACTORS,ClinVar_SV,ClinVar_SV_CLNSIG,ClinVar_SV_CLNACC
0,.,10_KN196480v1_fix:92599-138898,duplication,intron_variant,MODIFIER,KAT6B,ENSG00000281813,Transcript,ENST00000628038.3,protein_coding,...,-,-,-,-,-,-,-,-,-,-
1,.,10_KN196480v1_fix:92599-138898,duplication,intron_variant,MODIFIER,KAT6B,ENSG00000281813,Transcript,ENST00000628523.3,protein_coding,...,-,-,-,-,-,-,-,-,-,-
2,.,10_KN196480v1_fix:92599-138898,duplication,intron_variant,MODIFIER,KAT6B,ENSG00000281813,Transcript,ENST00000629233.3,protein_coding,...,-,-,-,-,-,-,-,-,-,-
3,.,10_KN196480v1_fix:92599-138898,duplication,intron_variant,MODIFIER,KAT6B,ENSG00000281813,Transcript,ENST00000629879.2,protein_coding,...,-,-,-,-,-,-,-,-,-,-
4,.,10_KN196480v1_fix:92599-138898,duplication,intron_variant,MODIFIER,KAT6B,ENSG00000281813,Transcript,ENST00000630001.4,protein_coding,...,-,-,-,-,-,-,-,-,-,-

In [ ]:
df.drop([
    "#Uploaded variant", "Allele", "Feature", "Biotype", "Exon", "Intron", 
    "HGVSc", "cDNA_position", "CDS_position", "Protein_position", 
    "Amino_acids", "Codons", "Existing_variant", "REF_ALLELE", 
    "UPLOADED_ALLELE", "Distance_to_transcript", "Feature_strand", "FLAGS", 
    "Symbol_source", "HGNC_ID", "MANE", "MANE_SELECT", "MANE_PLUS_CLINICAL", 
    "Transcript_support_level", "APPRIS", "CCDS", "SWISSPROT", "TREMBL", 
    "UNIPARC", "UNIPROT_ISOFORM", "REFSEQ_MATCH", "Transcript_source", 
    "REFSEQ_OFFSET", "GIVEN_REF", "USED_REF", "BAM_EDIT", "SIFT", "PolyPhen", 
    "HGVS_offset", "AF", "gnomADe_AF", "gnomADe_AFR_AF", "gnomADe_AMR_AF", 
    "gnomADe_ASJ_AF", "gnomADe_EAS_AF", "gnomADe_FIN_AF", "gnomADe_MID_AF", 
    "gnomADe_NFE_AF", "gnomADe_REMAINING_AF", "gnomADe_SAS_AF", "gnomADg_AF", 
    "gnomADg_AFR_AF", "gnomADg_AMI_AF", "gnomADg_AMR_AF", "gnomADg_ASJ_AF", 
    "gnomADg_EAS_AF", "gnomADg_FIN_AF", "gnomADg_MID_AF", "gnomADg_NFE_AF", 
    "gnomADg_REMAINING_AF", "gnomADg_SAS_AF", "Clinical_significance", 
    "Somatic_status", "Phenotype_or_disease", "Pubmed", "Motif_name", 
    "Motif_position", "High_info_position", "Motif_score_change", 
    "TRANSCRIPTION_FACTORS", "SpliceAI_pred_DP_AG", "SpliceAI_pred_DP_AL", 
    "SpliceAI_pred_DP_DG", "SpliceAI_pred_DP_DL", "SpliceAI_pred_DS_AG", 
    "SpliceAI_pred_DS AL", "SpliceAI_pred_DS_DG", "SpliceAI_pred_DS_DL", 
    "SpliceAI_pred_SYMBOL", "ClinPred", "SpliceAI_pred_DP_DL", "SpliceAI_pred_DS_AG", 
    "SpliceAI_pred_DS_AL", "SpliceAI_pred_DS_DG", "SpliceAI_pred_DS_DL", "SpliceAI_pred_SYMBOL", 
    "#Uploaded_variation", "HIGH_INF_POS", "MOTIF_SCORE_CHANGE", "TRANSCRIPTION_FACTORS", 
    "SpliceAI_pred_DP_AG", "SpliceAI_pred_DP_AL", "SpliceAI_pred_DP_DG",
    "SOMATIC", "PHENO", "PUBMED", "MOTIF_NAME", "MOTIF_POS", "EXON", "INTRON", "HGVSp",
    "gnomADg_FIN_AF", "gnomADg_MID_AF", "gnomADg_NFE_AF", "gnomADg_REMAINING_AF", "gnomADg_SAS_AF",
    "BIOTYPE", "SOURCE", "TSL", "HGVS_OFFSET", "DISTANCE", "STRAND", "HGVS_OFFSET", "SYMBOL_SOURCE", "CANONICAL", "VAR_SYNONYMS",
    "GENCODE_promoter", "GENCODE_promoter_type", "GENCODE_promoter_feature_id", "GENCODE_promoter_associated_gene", "CLIN_SIG",
    "Existing_variation", "Feature_type"
], axis=1, errors='ignore', inplace=True)

In [5]:
len(df)

6787

In [6]:
df.head(8)

,Location,Consequence,IMPACT,SYMBOL,Gene,ClinVar_SV,ClinVar_SV_CLNSIG,ClinVar_SV_CLNACC
0,10_KN196480v1_fix:92599-138898,intron_variant,MODIFIER,KAT6B,ENSG00000281813,-,-,-
1,10_KN196480v1_fix:92599-138898,intron_variant,MODIFIER,KAT6B,ENSG00000281813,-,-,-
2,10_KN196480v1_fix:92599-138898,intron_variant,MODIFIER,KAT6B,ENSG00000281813,-,-,-
3,10_KN196480v1_fix:92599-138898,intron_variant,MODIFIER,KAT6B,ENSG00000281813,-,-,-
4,10_KN196480v1_fix:92599-138898,intron_variant,MODIFIER,KAT6B,ENSG00000281813,-,-,-
5,10_KN196480v1_fix:92599-138898,intron_variant,MODIFIER,KAT6B,ENSG00000281813,-,-,-
6,10_KN196480v1_fix:92599-138898,intron_variant,MODIFIER,KAT6B,ENSG00000281813,-,-,-
7,10_KN196480v1_fix:92599-138898,"intron_variant,NMD_transcript_variant",MODIFIER,KAT6B,ENSG00000281813,-,-,-

In [7]:
cencus_genes = pd.read_csv("cosmic_census.csv")
cancer_genes = list(cencus_genes["Gene Symbol"])
cancer_genes1 = ["MYC", "MYCN", "EGFR", "ERBB2", "KRAS", "NRAS", "CDK4", "CDK6",
"MDM2", "CCND1", "FGF19", "MET", "ALK", "RET", "BRAF", "TP53", "RB1", "BRCA1", "BRCA2", "CDKN2A", "PTEN", "APC", "VHL", 
"STK11", "SMAD4", "NF1", "NF2", "TSC1", "TSC2", "MLH1", "MSH2"]
cancer_genes.extend(cancer_genes1)

In [8]:
present_genes = list(df["SYMBOL"]) 
mask = [True if (present_genes[i] in cancer_genes) else False for i in range(len(present_genes))]

df_probe = df[mask]

In [9]:
df_probe

,Location,Consequence,IMPACT,SYMBOL,Gene,ClinVar_SV,ClinVar_SV_CLNSIG,ClinVar_SV_CLNACC
0,10_KN196480v1_fix:92599-138898,intron_variant,MODIFIER,KAT6B,ENSG00000281813,-,-,-
1,10_KN196480v1_fix:92599-138898,intron_variant,MODIFIER,KAT6B,ENSG00000281813,-,-,-
2,10_KN196480v1_fix:92599-138898,intron_variant,MODIFIER,KAT6B,ENSG00000281813,-,-,-
3,10_KN196480v1_fix:92599-138898,intron_variant,MODIFIER,KAT6B,ENSG00000281813,-,-,-
4,10_KN196480v1_fix:92599-138898,intron_variant,MODIFIER,KAT6B,ENSG00000281813,-,-,-
...,...,...,...,...,...,...,...,...
4767,22:12539703-22009451,transcript_amplification,HIGH,CLTCL1,8218,-,-,-
4768,22:12539703-22009451,transcript_amplification,HIGH,CLTCL1,8218,-,-,-
4769,22:12539703-22009451,transcript_amplification,HIGH,CLTCL1,8218,-,-,-
4770,22:12539703-22009451,transcript_amplification,HIGH,CLTCL1,8218,-,-,-
4771,22:12539703-22009451,transcript_amplification,HIGH,CLTCL1,8218,-,-,-

In [10]:
df_probe.drop(["ClinVar_SV", "ClinVar_SV_CLNSIG", "ClinVar_SV_CLNACC"], axis = 1)

,Location,Consequence,IMPACT,SYMBOL,Gene
0,10_KN196480v1_fix:92599-138898,intron_variant,MODIFIER,KAT6B,ENSG00000281813
1,10_KN196480v1_fix:92599-138898,intron_variant,MODIFIER,KAT6B,ENSG00000281813
2,10_KN196480v1_fix:92599-138898,intron_variant,MODIFIER,KAT6B,ENSG00000281813
3,10_KN196480v1_fix:92599-138898,intron_variant,MODIFIER,KAT6B,ENSG00000281813
4,10_KN196480v1_fix:92599-138898,intron_variant,MODIFIER,KAT6B,ENSG00000281813
...,...,...,...,...,...
4767,22:12539703-22009451,transcript_amplification,HIGH,CLTCL1,8218
4768,22:12539703-22009451,transcript_amplification,HIGH,CLTCL1,8218
4769,22:12539703-22009451,transcript_amplification,HIGH,CLTCL1,8218
4770,22:12539703-22009451,transcript_amplification,HIGH,CLTCL1,8218
4771,22:12539703-22009451,transcript_amplification,HIGH,CLTCL1,8218

In [11]:
df_probe = df_probe.drop_duplicates(subset = ["Location", "SYMBOL", "Consequence"])
len(df_probe)

11

In [12]:
df_probe

,Location,Consequence,IMPACT,SYMBOL,Gene,ClinVar_SV,ClinVar_SV_CLNSIG,ClinVar_SV_CLNACC
0,10_KN196480v1_fix:92599-138898,intron_variant,MODIFIER,KAT6B,ENSG00000281813,-,-,-
7,10_KN196480v1_fix:92599-138898,"intron_variant,NMD_transcript_variant",MODIFIER,KAT6B,ENSG00000281813,-,-,-
9,10_KN196480v1_fix:92599-138898,"intron_variant,non_coding_transcript_variant",MODIFIER,KAT6B,ENSG00000281813,-,-,-
14,10_KN196480v1_fix:92599-138898,"coding_sequence_variant,3_prime_UTR_variant,in...",MODIFIER,KAT6B,ENSG00000281813,-,-,-
1675,20_MU273389v1_fix:152456-304912,transcript_ablation,HIGH,SRC,ENSG00000291971,-,-,-
1676,20_MU273389v1_fix:152456-304912,"feature_truncation,coding_sequence_variant,5_p...",HIGH,SRC,ENSG00000291971,-,-,-
1684,20_MU273389v1_fix:152456-304912,"feature_truncation,non_coding_transcript_exon_...",HIGH,SRC,ENSG00000291971,-,-,-
1685,20_MU273389v1_fix:152456-304912,upstream_gene_variant,MODIFIER,SRC,ENSG00000291971,-,-,-
1786,22:12539703-22009451,transcript_amplification,HIGH,MAPK1,ENSG00000100030,-,-,-
1976,22:12539703-22009451,transcript_amplification,HIGH,CLTCL1,ENSG00000070371,-,-,-
1993,22:12539703-22009451,transcript_amplification,HIGH,LZTR1,ENSG00000099949,-,-,-

In [21]:
df_probe.to_csv("filtered_CNV.txt")

In [18]:
df1 = pd.read_csv("filtered_SNV.txt", sep="\t", header = 0)
print(len(df1))

155

In [19]:
df1.head(10)

,#Uploaded_variation,Location,Allele,Consequence,IMPACT,SYMBOL,Gene,Feature_type,Feature,BIOTYPE,...,SpliceAI_pred_DS_AG,SpliceAI_pred_DS_AL,SpliceAI_pred_DS_DG,SpliceAI_pred_DS_DL,SpliceAI_pred_SYMBOL,ClinPred,PHENOTYPES,ClinVar_SV,ClinVar_SV_CLNSIG,ClinVar_SV_CLNACC
0,.,1:171636626-171636626,A,stop_gained,HIGH,MYOC,ENSG00000034971,Transcript,ENST00000037502.11,protein_coding,...,0.00,0.00,0.00,0.00,MYOC,-,MYOC-related_glaucoma__primary_open_angle+G2P+...,"nssv15149867,nssv15151118,nssv16867097,nssv168...","Pathogenic,""Pathogenic"",""Uncertain%20significa...","VCV000442386.2,VCV000442387.2,VCV001003645.3,V..."
1,.,1:171636626-171636626,A,stop_gained,HIGH,MYOC,ENSG00000034971,Transcript,ENST00000877923.1,protein_coding,...,0.00,0.00,0.00,0.00,MYOC,-,MYOC-related_glaucoma__primary_open_angle+G2P+...,"nssv15149867,nssv15151118,nssv16867097,nssv168...","Pathogenic,""Pathogenic"",""Uncertain%20significa...","VCV000442386.2,VCV000442387.2,VCV001003645.3,V..."
2,.,1:171636626-171636626,A,stop_gained,HIGH,MYOC,ENSG00000034971,Transcript,ENST00000971579.1,protein_coding,...,0.00,0.00,0.00,0.00,MYOC,-,MYOC-related_glaucoma__primary_open_angle+G2P+...,"nssv15149867,nssv15151118,nssv16867097,nssv168...","Pathogenic,""Pathogenic"",""Uncertain%20significa...","VCV000442386.2,VCV000442387.2,VCV001003645.3,V..."
3,.,1:171636626-171636626,A,stop_gained,HIGH,MYOC,4653,Transcript,NM_000261.2,protein_coding,...,0.00,0.00,0.00,0.00,MYOC,-,MYOC-related_glaucoma__primary_open_angle+G2P+...,"nssv15149867,nssv15151118,nssv16867097,nssv168...","Pathogenic,""Pathogenic"",""Uncertain%20significa...","VCV000442386.2,VCV000442387.2,VCV001003645.3,V..."
4,.,10:128106847-128106849,-,frameshift_variant,HIGH,MKI67,ENSG00000148773,Transcript,ENST00000368653.7,protein_coding,...,0.00,0.00,0.00,0.00,MKI67,-,-,"nssv15161644,nssv15161670,nssv15161864,nssv188...","Pathogenic,""Pathogenic"",""Pathogenic"",""Pathogen...","VCV000393995.3,VCV000441986.2,VCV000441987.2,V..."
5,.,10:128106847-128106849,-,frameshift_variant,HIGH,MKI67,ENSG00000148773,Transcript,ENST00000368654.8,protein_coding,...,0.00,0.00,0.00,0.00,MKI67,-,-,"nssv15161644,nssv15161670,nssv15161864,nssv188...","Pathogenic,""Pathogenic"",""Pathogenic"",""Pathogen...","VCV000393995.3,VCV000441986.2,VCV000441987.2,V..."
6,.,10:128106847-128106849,-,frameshift_variant,HIGH,MKI67,ENSG00000148773,Transcript,ENST00000935442.1,protein_coding,...,0.00,0.00,0.00,0.00,MKI67,-,-,"nssv15161644,nssv15161670,nssv15161864,nssv188...","Pathogenic,""Pathogenic"",""Pathogenic"",""Pathogen...","VCV000393995.3,VCV000441986.2,VCV000441987.2,V..."
7,.,10:128106847-128106849,-,frameshift_variant,HIGH,MKI67,4288,Transcript,NM_001145966.2,protein_coding,...,0.00,0.00,0.00,0.00,MKI67,-,-,"nssv15161644,nssv15161670,nssv15161864,nssv188...","Pathogenic,""Pathogenic"",""Pathogenic"",""Pathogen...","VCV000393995.3,VCV000441986.2,VCV000441987.2,V..."
8,.,10:128106847-128106849,-,frameshift_variant,HIGH,MKI67,4288,Transcript,NM_002417.5,protein_coding,...,0.00,0.00,0.00,0.00,MKI67,-,-,"nssv15161644,nssv15161670,nssv15161864,nssv188...","Pathogenic,""Pathogenic"",""Pathogenic"",""Pathogen...","VCV000393995.3,VCV000441986.2,VCV000441987.2,V..."
9,.,10:128106847-128106849,-,frameshift_variant,HIGH,MKI67,4288,Transcript,XM_006717864.4,protein_coding,...,0.00,0.00,0.00,0.00,MKI67,-,-,"nssv15161644,nssv15161670,nssv15161864,nssv188...","Pathogenic,""Pathogenic"",""Pathogenic"",""Pathogen...","VCV000393995.3,VCV000441986.2,VCV000441987.2,V..."

In [20]:
df1.drop([
    "#Uploaded variant", "Feature", "Biotype", "Exon", "Intron", 
    "HGVSc", "cDNA_position", "CDS_position", "Protein_position", 
    "Amino_acids", "Codons", "Existing_variant", "REF_ALLELE", 
    "UPLOADED_ALLELE", "Distance_to_transcript", "Feature_strand", "FLAGS", 
    "Symbol_source", "HGNC_ID", "MANE", "MANE_SELECT", "MANE_PLUS_CLINICAL", 
    "Transcript_support_level", "APPRIS", "CCDS", "SWISSPROT", "TREMBL", 
    "UNIPARC", "UNIPROT_ISOFORM", "REFSEQ_MATCH", "Transcript_source", 
    "REFSEQ_OFFSET", "GIVEN_REF", "USED_REF", "BAM_EDIT", "SIFT", "PolyPhen", 
    "HGVS_offset", "AF", "gnomADe_AF", "gnomADe_AFR_AF", "gnomADe_AMR_AF", 
    "gnomADe_ASJ_AF", "gnomADe_EAS_AF", "gnomADe_FIN_AF", "gnomADe_MID_AF", 
    "gnomADe_NFE_AF", "gnomADe_REMAINING_AF", "gnomADe_SAS_AF", "gnomADg_AF", 
    "gnomADg_AFR_AF", "gnomADg_AMI_AF", "gnomADg_AMR_AF", "gnomADg_ASJ_AF", 
    "gnomADg_EAS_AF", "gnomADg_FIN_AF", "gnomADg_MID_AF", "gnomADg_NFE_AF", 
    "gnomADg_REMAINING_AF", "gnomADg_SAS_AF", "Clinical_significance", 
    "Somatic_status", "Phenotype_or_disease", "Pubmed", "Motif_name", 
    "Motif_position", "High_info_position", "Motif_score_change", 
    "TRANSCRIPTION_FACTORS", "SpliceAI_pred_DP_AG", "SpliceAI_pred_DP_AL", 
    "SpliceAI_pred_DP_DG", "SpliceAI_pred_DP_DL", "SpliceAI_pred_DS_AG", 
    "SpliceAI_pred_DS AL", "SpliceAI_pred_DS_DG", "SpliceAI_pred_DS_DL", 
    "SpliceAI_pred_SYMBOL", "ClinPred", "SpliceAI_pred_DP_DL", "SpliceAI_pred_DS_AG", 
    "SpliceAI_pred_DS_AL", "SpliceAI_pred_DS_DG", "SpliceAI_pred_DS_DL", "SpliceAI_pred_SYMBOL", 
    "#Uploaded_variation", "HIGH_INF_POS", "MOTIF_SCORE_CHANGE", "TRANSCRIPTION_FACTORS", 
    "SpliceAI_pred_DP_AG", "SpliceAI_pred_DP_AL", "SpliceAI_pred_DP_DG",
    "SOMATIC", "PHENO", "PUBMED", "MOTIF_NAME", "MOTIF_POS", "EXON", "INTRON",
    "gnomADg_FIN_AF", "gnomADg_MID_AF", "gnomADg_NFE_AF", "gnomADg_REMAINING_AF", "gnomADg_SAS_AF",
    "BIOTYPE", "SOURCE", "TSL", "HGVS_OFFSET", "DISTANCE", "STRAND", "HGVS_OFFSET"
], axis=1, errors='ignore', inplace=True)

In [21]:
df1 = df1.drop_duplicates(subset = ["Location", "Consequence", "SYMBOL", "Existing_variation", "CLIN_SIG"])

In [22]:
len(df1)
# new_df1 = df1[df1.CLIN_SIG == 'likely_pathogenic,pathogenic']

14

In [23]:
df1.head(14)

,Location,Allele,Consequence,IMPACT,SYMBOL,Gene,Feature_type,HGVSp,Existing_variation,SYMBOL_SOURCE,CLIN_SIG,PHENOTYPES,ClinVar_SV,ClinVar_SV_CLNSIG,ClinVar_SV_CLNACC
0,1:171636626-171636626,A,stop_gained,HIGH,MYOC,ENSG00000034971,Transcript,ENSP00000037502.5:p.Arg272Ter,"rs202176570,CM005409,CM087800,COSV50674466",HGNC,uncertain_significance,MYOC-related_glaucoma__primary_open_angle+G2P+...,"nssv15149867,nssv15151118,nssv16867097,nssv168...","Pathogenic,""Pathogenic"",""Uncertain%20significa...","VCV000442386.2,VCV000442387.2,VCV001003645.3,V..."
4,10:128106847-128106849,-,frameshift_variant,HIGH,MKI67,ENSG00000148773,Transcript,ENSP00000357642.3:p.Thr1304ArgfsTer7,rs145960091,HGNC,-,-,"nssv15161644,nssv15161670,nssv15161864,nssv188...","Pathogenic,""Pathogenic"",""Pathogenic"",""Pathogen...","VCV000393995.3,VCV000441986.2,VCV000441987.2,V..."
11,11:46726628-46726628,G,splice_donor_variant,HIGH,F2,ENSG00000180210,Transcript,-,"rs111566191,COSV61314973",HGNC,-,PREGNANCY_LOSS__RECURRENT__SUSCEPTIBILITY_TO__...,"nssv15150306,nssv15150623,nssv16867095,nssv179...","Pathogenic,""Pathogenic"",""Pathogenic"",""Pathogen...","VCV000441904.2,VCV000441903.2,VCV000997825.1,V..."
36,12:45926923-45926925,-,frameshift_variant,HIGH,SCAF11,ENSG00000139218,Transcript,ENSP00000358374.3:p.Glu926LysfsTer8,rs749292193,HGNC,-,-,"nssv15161620,nssv15161414,nssv15161422,nssv151...","Pathogenic,""Pathogenic"",""Pathogenic"",""Pathogen...","VCV000268075.3,VCV000441983.2,VCV000441984.2,V..."
50,14:99652231-99652231,A,stop_gained,HIGH,HHIPL1,ENSG00000182218,Transcript,ENSP00000330601.5:p.Ser88Ter,"rs1298712430,COSV58094119",HGNC,-,-,"nssv15161629,nssv15161107,nssv15161424,nssv151...","Pathogenic,""Pathogenic"",""Pathogenic"",""Pathogen...","VCV000395470.3,VCV000155306.2,VCV000443977.2,V..."
59,15:90233883-90233883,A,start_lost,HIGH,CIB1,ENSG00000185043,Transcript,ENSP00000333873.6:p.Met1?,rs769146522,HGNC,-,CIB1-related_epidermodysplasia_verruciformis+G...,"nssv15125410,nssv15149616,nssv15124620,nssv151...","Pathogenic,""Pathogenic"",""Uncertain%20significa...","VCV000401851.2,VCV000395145.3,VCV000399079.2,V..."
66,16:56886516-56886516,A,stop_gained,HIGH,SLC12A3,ENSG00000070915,Transcript,ENSP00000568267.1:p.Trp690Ter,rs777686519,HGNC,-,"GITELMAN_SYNDROME+MIM_morbid+ENSG00000070915,G...","nssv15148703,nssv15150639,nssv15151292,nssv151...","Pathogenic,""Pathogenic"",""Pathogenic"",""Uncertai...","VCV000395502.3,VCV000443120.2,VCV000443121.2,V..."
67,22:44862416-44862416,T,stop_gained,HIGH,ARHGAP8,ENSG00000241484,Transcript,ENSP00000348407.6:p.Glu375Ter,rs144526462,HGNC,-,-,"nssv15146973,nssv15150031,nssv15150491,nssv162...","Pathogenic,""Pathogenic"",""Pathogenic"",""Pathogen...","VCV000253509.1,VCV000394709.3,VCV000395140.3,V..."
97,22:44862416-44862416,T,stop_gained,HIGH,PRR5-ARHGAP8,553158,Transcript,NP_851851.3:p.Glu506Ter,rs144526462,EntrezGene,-,-,"nssv15146973,nssv15150031,nssv15150491,nssv162...","Pathogenic,""Pathogenic"",""Pathogenic"",""Pathogen...","VCV000253509.1,VCV000394709.3,VCV000395140.3,V..."
99,3:13328895-13328895,A,stop_gained,HIGH,NUP210,ENSG00000132182,Transcript,ENSP00000254508.5:p.Gln1388Ter,"rs145576034,COSV54402780",HGNC,-,-,"nssv18846610,nssv15149909,nssv15151098,nssv179...","Pathogenic,""Pathogenic"",""Pathogenic"",""Pathogen...","VCV003242334.1,VCV000443464.2,VCV000441705.2,V..."
111,3:150660125-150660125,A,stop_gained,HIGH,ERICH6,ENSG00000163645,Transcript,ENSP00000295910.6:p.Arg587Ter,"rs370274830,COSV55799857,COSV99901956",HGNC,-,-,"nssv15149891,nssv15151839,nssv15148025,nssv183...","Pathogenic,""Pathogenic"",""Pathogenic"",""Pathogen...","VCV000442401.2,VCV000442400.2,VCV000145614.2,V..."
115,6:107893550-107893551,-,frameshift_variant,HIGH,SEC63,ENSG00000025796,Transcript,ENSP00000357998.4:p.Lys535AsnfsTer28,rs752868449,HGNC,"likely_pathogenic,pathogenic",POLYCYSTIC_LIVER_DISEASE_2_WITH_OR_WITHOUT_KID...,"nssv15161859,nssv15161868,nssv15148895,nssv179...","Pathogenic,""Pathogenic"",""Pathogenic"",""Pathogen...","VCV000443497.2,VCV000443496.2,VCV000150937.2,V..."
127,9:113483003-113483005,-,frameshift_variant,HIGH,RGS3,5998,Transcript,NP_001269852.1:p.Tyr32CysfsTer18,rs368227112,EntrezGene,-,-,"nssv15128159,nssv15150554,nssv15146972,nssv151...","Pathogenic,""Pathogenic"",""Pathogenic"",""Pathogen...","VCV000400183.2,VCV000395707.3,VCV000253402.2,V..."
128,9:137101890-137101894,-,frameshift_variant,HIGH,LOC124902313,124902313,Transcript,XP_047280292.1:p.His46LeufsTer123,rs1830826072,EntrezGene,-,MAN1B1-related_intellectual_developmental_diso...,"nssv15128159,nssv15150554,nssv15146972,nssv151...","Pathogenic,""Pathogenic"",""Pathogenic"",""Pathogen...","VCV000400183.2,VCV000395707.3,VCV000253402.2,V..."

In [24]:
df1.to_csv("filtered_SNV.txt", sep = "\t")

In [6]:
df2 = pd.read_csv("filtered_SV.txt", sep = "\t", header = 0)
len(df2)

12

In [7]:
pattern = "pathogenic"
df2 = df2[df2['ClinVar_SV_CLNSIG'].str.contains(pattern, na=False)]

In [8]:
len(df2)

12

In [9]:
df2.head()

,Unnamed: 0,Location,Consequence,IMPACT,SYMBOL,Gene,Feature_type,Existing_variation,SYMBOL_SOURCE,CANONICAL,CLIN_SIG,PHENOTYPES,ClinVar_SV,ClinVar_SV_CLNSIG,ClinVar_SV_CLNACC,clinvar_score
0,4,10:53455357-53455357,feature_truncation,HIGH,CDH23,ENSG00000107736,Transcript,-,HGNC,YES,-,-,"nssv15161644,nssv15161670,nssv15161864,nssv188...","Pathogenic,""Pathogenic"",""Pathogenic"",""Pathogen...","VCV000393995.3,VCV000441986.2,VCV000441987.2,V...",3
1,6,10:60074057-60074057,"feature_truncation,coding_sequence_variant",HIGH,ANK3,ENSG00000151150,Transcript,-,HGNC,YES,-,INTELLECTUAL_DEVELOPMENTAL_DISORDER__AUTOSOMAL...,"nssv15161644,nssv15161670,nssv15161864,nssv188...","Pathogenic,""Pathogenic"",""Pathogenic"",""Pathogen...","VCV000393995.3,VCV000441986.2,VCV000441987.2,V...",3
2,7,10:60074057-60074057,feature_truncation,HIGH,CABCOCO1,ENSG00000183346,Transcript,-,HGNC,YES,-,INTELLECTUAL_DEVELOPMENTAL_DISORDER__AUTOSOMAL...,"nssv15161644,nssv15161670,nssv15161864,nssv188...","Pathogenic,""Pathogenic"",""Pathogenic"",""Pathogen...","VCV000393995.3,VCV000441986.2,VCV000441987.2,V...",3
3,10,10:61692464-61692464,feature_truncation,HIGH,ANK3,ENSG00000151150,Transcript,-,HGNC,YES,-,-,"nssv15161644,nssv15161670,nssv15161864,nssv188...","Pathogenic,""Pathogenic"",""Pathogenic"",""Pathogen...","VCV000393995.3,VCV000441986.2,VCV000441987.2,V...",3
4,11,10:61692464-61692464,"feature_truncation,intron_variant",HIGH,CABCOCO1,ENSG00000183346,Transcript,-,HGNC,YES,-,-,"nssv15161644,nssv15161670,nssv15161864,nssv188...","Pathogenic,""Pathogenic"",""Pathogenic"",""Pathogen...","VCV000393995.3,VCV000441986.2,VCV000441987.2,V...",3

In [ ]:
df2.drop([
    "#Uploaded variant", "Allele", "Feature", "Biotype", "Exon", "Intron", 
    "HGVSc", "cDNA_position", "CDS_position", "Protein_position", 
    "Amino_acids", "Codons", "Existing_variant", "REF_ALLELE", 
    "UPLOADED_ALLELE", "Distance_to_transcript", "Feature_strand", "FLAGS", 
    "Symbol_source", "HGNC_ID", "MANE", "MANE_SELECT", "MANE_PLUS_CLINICAL", 
    "Transcript_support_level", "APPRIS", "CCDS", "SWISSPROT", "TREMBL", 
    "UNIPARC", "UNIPROT_ISOFORM", "REFSEQ_MATCH", "Transcript_source", 
    "REFSEQ_OFFSET", "GIVEN_REF", "USED_REF", "BAM_EDIT", "SIFT", "PolyPhen", 
    "HGVS_offset", "AF", "gnomADe_AF", "gnomADe_AFR_AF", "gnomADe_AMR_AF", 
    "gnomADe_ASJ_AF", "gnomADe_EAS_AF", "gnomADe_FIN_AF", "gnomADe_MID_AF", 
    "gnomADe_NFE_AF", "gnomADe_REMAINING_AF", "gnomADe_SAS_AF", "gnomADg_AF", 
    "gnomADg_AFR_AF", "gnomADg_AMI_AF", "gnomADg_AMR_AF", "gnomADg_ASJ_AF", 
    "gnomADg_EAS_AF", "gnomADg_FIN_AF", "gnomADg_MID_AF", "gnomADg_NFE_AF", 
    "gnomADg_REMAINING_AF", "gnomADg_SAS_AF", "Clinical_significance", 
    "Somatic_status", "Phenotype_or_disease", "Pubmed", "Motif_name", 
    "Motif_position", "High_info_position", "Motif_score_change", 
    "TRANSCRIPTION_FACTORS", "SpliceAI_pred_DP_AG", "SpliceAI_pred_DP_AL", 
    "SpliceAI_pred_DP_DG", "SpliceAI_pred_DP_DL", "SpliceAI_pred_DS_AG", 
    "SpliceAI_pred_DS AL", "SpliceAI_pred_DS_DG", "SpliceAI_pred_DS_DL", 
    "SpliceAI_pred_SYMBOL", "ClinPred", "SpliceAI_pred_DP_DL", "SpliceAI_pred_DS_AG", 
    "SpliceAI_pred_DS_AL", "SpliceAI_pred_DS_DG", "SpliceAI_pred_DS_DL", "SpliceAI_pred_SYMBOL", 
    "#Uploaded_variation", "HIGH_INF_POS", "MOTIF_SCORE_CHANGE", "TRANSCRIPTION_FACTORS", 
    "SpliceAI_pred_DP_AG", "SpliceAI_pred_DP_AL", "SpliceAI_pred_DP_DG",
    "SOMATIC", "PHENO", "PUBMED", "MOTIF_NAME", "MOTIF_POS", "EXON", "INTRON", "HGVSp",
    "gnomADg_FIN_AF", "gnomADg_MID_AF", "gnomADg_NFE_AF", "gnomADg_REMAINING_AF", "gnomADg_SAS_AF",
    "BIOTYPE", "SOURCE", "TSL", "HGVS_OFFSET", "DISTANCE", "STRAND", "HGVS_OFFSET",
    "GENCODE_promoter", "GENCODE_promoter_type", "GENCODE_promoter_feature_id", "GENCODE_promoter_associated_gene",
    "VAR_SYNONYMS"
], axis=1, errors='ignore', inplace=True)

In [27]:
df2.head()

,Location,Consequence,IMPACT,SYMBOL,Gene,Feature_type,Existing_variation,SYMBOL_SOURCE,CANONICAL,CLIN_SIG,PHENOTYPES,ClinVar_SV,ClinVar_SV_CLNSIG,ClinVar_SV_CLNACC
4,10:53455357-53455357,feature_truncation,HIGH,CDH23,ENSG00000107736,Transcript,-,HGNC,YES,-,-,"nssv15161644,nssv15161670,nssv15161864,nssv188...","Pathogenic,""Pathogenic"",""Pathogenic"",""Pathogen...","VCV000393995.3,VCV000441986.2,VCV000441987.2,V..."
5,10:53455357-53455357,feature_truncation,HIGH,CDH23,64072,Transcript,-,EntrezGene,YES,-,-,"nssv15161644,nssv15161670,nssv15161864,nssv188...","Pathogenic,""Pathogenic"",""Pathogenic"",""Pathogen...","VCV000393995.3,VCV000441986.2,VCV000441987.2,V..."
6,10:60074057-60074057,"feature_truncation,coding_sequence_variant",HIGH,ANK3,ENSG00000151150,Transcript,-,HGNC,YES,-,INTELLECTUAL_DEVELOPMENTAL_DISORDER__AUTOSOMAL...,"nssv15161644,nssv15161670,nssv15161864,nssv188...","Pathogenic,""Pathogenic"",""Pathogenic"",""Pathogen...","VCV000393995.3,VCV000441986.2,VCV000441987.2,V..."
7,10:60074057-60074057,feature_truncation,HIGH,CABCOCO1,ENSG00000183346,Transcript,-,HGNC,YES,-,INTELLECTUAL_DEVELOPMENTAL_DISORDER__AUTOSOMAL...,"nssv15161644,nssv15161670,nssv15161864,nssv188...","Pathogenic,""Pathogenic"",""Pathogenic"",""Pathogen...","VCV000393995.3,VCV000441986.2,VCV000441987.2,V..."
8,10:60074057-60074057,feature_truncation,HIGH,CABCOCO1,219621,Transcript,-,EntrezGene,YES,-,INTELLECTUAL_DEVELOPMENTAL_DISORDER__AUTOSOMAL...,"nssv15161644,nssv15161670,nssv15161864,nssv188...","Pathogenic,""Pathogenic"",""Pathogenic"",""Pathogen...","VCV000393995.3,VCV000441986.2,VCV000441987.2,V..."

In [29]:
def clinvar_score(clnsig):
    if pd.isna(clnsig):
        return 0
    
    s = clnsig.lower()
    
    if "pathogenic" in s:
        return 3
    elif "likely%20pathogenic" in s or "likely pathogenic" in s:
        return 2
    elif "uncertain" in s:
        return 1
    else:
        return 0

df2["clinvar_score"] = df2["ClinVar_SV_CLNSIG"].apply(clinvar_score)

df_sorted = df2.sort_values(
    ["Location", "SYMBOL", "clinvar_score"],
    ascending=[True, True, False]
)

df2 = df_sorted.drop_duplicates(subset=["Location", "SYMBOL"], keep="first")

In [30]:
len(df2)

12

In [31]:
df2.to_csv("filtered_SV.txt", sep = "\t")